### PR TITLE
URL-decoding query and form parameters + decoding `FormData`

### LINKED ISSUE #170: URL-decode the textual params coming from the GET query or POST body

### LINKED ISSUE #321: URL-decode all inputs
- [ ] parameters : #170 
- [ ] (form) bodies : see commit https://github.com/scotty-web/scotty/commit/2a7db35ed3ba02cd84a42d4c3f5c325f4d67dad9 and PR #216 
- [x] pattern matching doesn't work against url-encoded path segments #262 

related : #8 

closes #170

### PR DESCRIPTION
**Pull request by pbrinkmeier**
Hiya, first time contributor.

This PR adds

- Tests for URL-decoding in `queryParam` and `formParam`
- A current implementation of the `formData` action from #216 

Let me know if this looks good to you guys or if I need to change anything.

closes #321 , closes #170 .

### CODE REVIEW

**Comment by ocramz** [comment]
thank you @pbrinkmeier ! I'll take a look soon.

**Review by ocramz — COMMENTED** [review]
Thank you! Looks good but just a minor comment in ScottySpec, I think we should reuse the implementation from hspec-wai (unless I'm missing something).

Edit: Also could you please add a line in the Changelog describing your changes?

File: test/Web/ScottySpec.hs [hunk 1]
```diff
@@ -41,6 +47,16 @@ main = hspec spec
...
 availableMethods = [GET, POST, HEAD, PUT, PATCH, DELETE, OPTIONS]
 
+data SearchForm = SearchForm
+  { sfQuery :: Text
+  , sfYear :: Int
+  } deriving (Generic)
+
+instance FromForm SearchForm where
+
+postForm :: ByteString -> LBS.ByteString -> WaiSession st SResponse
```
[the remark this answers is not in the document]
Comment (pbrinkmeier) [reply test/Web/ScottySpec.hs:57]: Ah, I did this for two reasons: Mostly because `postHtmlForm` turns regular Haskell strings into url-encoded strings before doing the request, so using this custom one makes the encoding more explicit in the tests. This makes them easier to read to me but I realise that's personal preference.

Second reason is that `postForm` was already present in this module, I just moved it to the top level for code reuse.

Happy to change it either way :+1:  Let me know :)

File: test/Web/ScottySpec.hs [hunk 2]
```diff
@@ -268,16 +286,28 @@ spec = do
...
+
+        it "decodes URL-encoding" $ do
+          postForm "/search" "sfQuery=Kurf%C3%BCrstendamm&sfYear=2024" `shouldRespondWith` "Kurfürstendamm"
+
+        it "returns 400 when the form is malformed" $ do
+          postForm "/search" "sfQuery=Haskell" `shouldRespondWith` 400
 
     describe "formParam" $ do
-      let
-        postForm p bdy = request "POST" p [("Content-Type","application/x-www-form-urlencoded")] bdy
```
Comment (pbrinkmeier) [inline test/Web/ScottySpec.hs:274]: This is where I got the implementation from.

**Comment by pbrinkmeier** [comment]
I added the changelog entry

**Comment by pbrinkmeier** [comment]
Fixed the conflict in `changelog.md`

File: Web/Scotty/Action.hs [hunk 3]
```diff
@@ -354,6 +363,19 @@ jsonData = do
...
 
+-- | Parse the request body as @x-www-form-urlencoded@ form data and return it.
+--
+--   The form is parsed using 'urlDecodeAsForm'. If that returns 'Left', the
+--   status is set to 400 and an exception is thrown.
+--
+-- NB : Internally this uses 'body'.
+formData :: (FromForm a, MonadIO m) => ActionT m a
+formData = do
+  b <- body
```
Comment (ocramz) [inline Web/Scotty/Action.hs:374]: Does `body` preserve the request body across calls to `next`? see #308

**Review by ocramz — COMMENTED** [review]
I would like to understand how much does the new function overlap in functionality with `formParams` and related. Also, I'm not sure using `body` is a good idea (depends on whether it respects #147 or not)

File: Web/Scotty/Action.hs [hunk 4]
```diff
@@ -354,6 +363,19 @@ jsonData = do
         A.Error err -> throwIO $ FailedToParseJSON b $ T.pack err
         A.Success a -> return a
 
+-- | Parse the request body as @x-www-form-urlencoded@ form data and return it.
+--
+--   The form is parsed using 'urlDecodeAsForm'. If that returns 'Left', the
+--   status is set to 400 and an exception is thrown.
+--
+-- NB : Internally this uses 'body'.
+formData :: (FromForm a, MonadIO m) => ActionT m a
```
[the remark this answers is not in the document]
Comment (pbrinkmeier) [reply Web/Scotty/Action.hs:372]: `formData` could be rewritten in terms of `formParams`, [`Form`](https://hackage.haskell.org/package/http-api-data-0.6/docs/Web-FormUrlEncoded.html#t:Form) and [`fromForm`](https://hackage.haskell.org/package/http-api-data-0.6/docs/Web-FormUrlEncoded.html#v:fromForm).

Which shows that yes, it is basically just support for a new encoding.

I initially added this because it was mentioned in #321 but I don't personally think that this is important functionality...

File: Web/Scotty/Action.hs (hunk 3 above)
Comment (pbrinkmeier) [reply Web/Scotty/Action.hs:374]: I'm not 100% what the desired behavior is, I assumed this was "right" because of the way `jsonData` is written :)

Should I add a test here?

Comment (pbrinkmeier) [reply Web/Scotty/Action.hs:374]: image

Internally, both `formParams` and `formData` use `getBodyAction` which I believe leads to consistent behavior unless I'm missing something.

Comment (ocramz) [reply Web/Scotty/Action.hs:374]: Correct! (beautiful diagram btw, how did you make it?) 

Basically this "lazier" parsing of request bodies (underneath the implementation of `files`, `formParams` etc.) is what I introduced in #369 and I think it would make sense for form parameters too.

Comment (pbrinkmeier) [reply Web/Scotty/Action.hs:374]: The diagram is made using [plant UML](https://plantuml.com), basically a text-based UML tool. Getting the call graph from Haskell isn't automatic tho, I did that by hand. Below is the source code for it.

<details>

```plantuml
@startuml
skinparam dpi 300

hide members
hide circle

package "Web.Scotty.Action" {
    formParams -down-> "Web.Scotty.Internal.Types.formParamsAndFilesWith"
    formData -down-> body
    body -down-> "Web.Scotty.Internal.Types.envBody"
}

package "Web.Scotty.Internal.Types" {
    formParamsAndFilesWith -left-> envFormDataAction
    envFormDataAction -down-> "Web.Scotty.Body.getFormParamsAndFilesAction"
    envBody -down-> Web.Scotty.Body.getBodyAction
}

note top of Web.Scotty.Internal.Types.envFormDataAction
Initialized by mkEnv
end note

note top of Web.Scotty.Internal.Types.envBody
Initialized by mkEnv
end note

package "Web.Scotty.Body" {
    getFormParamsAndFilesAction -down-> getBodyAction
    getFormParamsAndFilesAction -right-> parseRequestBodyExBS
    parseRequestBodyExBS -down-> "Network.Wai.Parse.sinkRequestBodyEx"
}

package "Network.Wai.Parse" {
    sinkRequestBodyEx -down-> conduitRequestBodyEx
    conduitRequestBodyEx -down-> "Network.HTTP.Types.parseSimpleQuery"
}

package Network.HTTP.Types {
    parseSimpleQuery -right-> parseQuery
    parseQuery -right-> urlDecode
}
@enduml
```

</details>

**Comment by pbrinkmeier** [comment]
I am still not entirely sure how to go forward with `formData`. Should I just remove it or rewrite it in terms of `formParams`?

**Comment by ocramz** [comment]
I think rewriting it in terms of formParams would be a great way forward!

**Comment by ocramz** [comment]
@pbrinkmeier looks good but why do we need the 'reverse' in 'paramListToForm'? the data comes from a hashmap anyway. Or am I missing something?

File: Web/Scotty/Action.hs [hunk 5]
```diff
@@ -354,6 +364,25 @@ jsonData = do
...
+formData = do
+  form <- paramListToForm <$> formParams
+  case fromForm form of
+    Left err -> throwIO $ MalformedForm err
+    Right value -> return value
+  where
+    -- This rather contrived implementation uses cons and reverse to avoid quadratic complexity (e.g. using HashMap.insertWith (++)).
+    -- It iterates over all parameters, prepending values for duplicate keys and reverses all hashmap entries afterwards.
+    paramListToForm :: [Param] -> Form
+    paramListToForm = Form . fmap reverse . foldl' (\f (k, v) -> HashMap.alter (prependValue v) k f) HashMap.empty
```
Comment (ocramz) [inline Web/Scotty/Action.hs:381]: > It iterates over all parameters, prepending values for duplicate keys and reverses all hashmap entries afterwards.

this describes the implementation, but a comment should explain _why_ we need this construction in the first place.

**Review by ocramz — COMMENTED** [review]
👍 

Just a changelog conflict to resolve and a comment to clarify why an implementation looks the way it does.

File: Web/Scotty/Action.hs (hunk 5 above)
Comment (pbrinkmeier) [reply Web/Scotty/Action.hs:381]: Ah, the reason is given in the first line:

> to avoid quadratic complexity (e.g. using HashMap.insertWith (++))

Comment (pbrinkmeier) [reply Web/Scotty/Action.hs:381]: Perhaps I could change it to "avoid quadratic complexity [...] when constructing a `Form` from a list of `Param`s.

Comment (ocramz) [reply Web/Scotty/Action.hs:381]: Yes this would be helpful!

**Review by ocramz — APPROVED** [review]
Thank you @pbrinkmeier , all good! 👍
