### PR TITLE
Handle exceptions from scotty as ScottyException

### LINKED ISSUE #338: 'status' and 'raiseStatus' (and 'redirect') overlap in functionality
One could `raiseStatus 200 "potato"` and it would be thrown as an exception, for example.

Also the redirect mechanism could be improved while we're at this. Eg. if you `raiseStatus 308 "/foo/bar"` you get `redirect`ed.

While a breaking change with the current implementation, the new behaviour would align better with users' expectations.

We can use the predicates defined here to inspect HTTP status codes and act accordingly (i.e. throw an exception or not) : https://hackage.haskell.org/package/http-types-0.12.3/docs/Network-HTTP-Types.html#v:statusIsInformational

### PR DESCRIPTION
**Pull request by fumieval**
This change replaces the use of `StatusError` by `ScottyException`. The idea is to avoid returning a error response in an arbitrary format and make it more reasonable to catch them, because catching `StatusError` doesn't make much sense

For the sake of compatibility, I kept the StatusError type but I think it should eventually be deprecated.

closes #338

### CODE REVIEW

File: Web/Scotty.hs [hunk 1]
```diff
@@ -57,8 +58,7 @@ import Network.Socket (Socket)
 import Network.Wai (Application, Middleware, Request, StreamingBody)
 import Network.Wai.Handler.Warp (Port)
 
-import Web.Scotty.Internal.Types (ScottyT, ActionT, ErrorHandler, Param, RoutePattern, Options, defaultOptions, File, Kilobytes, ScottyState, defaultScottyState, StatusError(..), Content(..))
-
+import Web.Scotty.Internal.Types hiding (Application, Middleware)
```
Comment (ocramz) [inline Web/Scotty.hs:61]: I find it easier to follow if imports are explicit (I don't use LSP)

File: Web/Scotty/Action.hs [hunk 2]
```diff
@@ -132,6 +132,39 @@ actionErrorHandler = Handler $ \case
   AENext -> next
   AEFinish -> return ()
 
+-- | Default, unscented handler for exceptions from scotty
```
Comment (ocramz) [inline Web/Scotty/Action.hs:135]: what does unscented mean here? please clarify

File: Web/Scotty/Action.hs [hunk 3]
```diff
@@ -132,6 +132,39 @@ actionErrorHandler = Handler $ \case
...
+scottyExceptionHandler :: MonadIO m => ErrorHandler m
+scottyExceptionHandler = Handler $ \case
+  RequestTooLarge -> do
+    status status413
+    text "Request body is too large"
+  MalformedJSON bs err -> do
+    status status400
+    text $ T.unlines
+      [ "jsonData: malformed"
+      , "Body: " <> decodeUtf8Lenient (BL.toStrict bs)
```
Comment (ocramz) [inline Web/Scotty/Action.hs:145]: do we really need to do a full copy and decode here?

File: Web/Scotty/Action.hs [hunk 4]
```diff
@@ -314,24 +338,24 @@ formParam = paramWith FormParam envFormParams status400
...
+queryParam = paramWith QueryParameterNotFound envQueryParams
 
 -- | Look up a capture parameter. Returns 'Nothing' if the parameter is not found or cannot be parsed at the right type.
 --
 -- NB : Doesn't throw exceptions. In particular, route pattern matching will not continue, so developers
 -- must 'raiseStatus' or 'throw' to signal something went wrong.
 --
 -- /Since: FIXME/
-captureParamMaybe :: (Parsable a, Monad m) => T.Text -> ActionT m (Maybe a)
+captureParamMaybe :: (Parsable a, MonadIO m) => T.Text -> ActionT m (Maybe a)
```
Comment (ocramz) [inline Web/Scotty/Action.hs:350]: why do we need a MonadIO constraint?

File: Web/Scotty/Trans.hs [hunk 5]
```diff
@@ -51,25 +52,26 @@ module Web.Scotty.Trans
...
-import Network.HTTP.Types (status404)
+import Network.HTTP.Types (status404, status413, status500)
 import Network.Socket (Socket)
 import qualified Network.Wai as W (Application, Middleware, Response, responseBuilder)
 import Network.Wai.Handler.Warp (Port, runSettings, runSettingsSocket, setPort, getPort)
 
 import Web.Scotty.Action
 import Web.Scotty.Route
-import Web.Scotty.Internal.Types (ScottyT(..), defaultScottyState, Application, RoutePattern, Options(..), defaultOptions, RouteOptions(..), defaultRouteOptions, ErrorHandler, Kilobytes, File, addMiddleware, setHandler, updateMaxRequestBodySize, routes, middlewares, ScottyException(..), ScottyState, defaultScottyState, StatusError(..), Content(..))
+import Web.Scotty.Internal.Types
```
Comment (ocramz) [inline Web/Scotty/Trans.hs:69]: explicit imports please (I added them in 0.20)

**Review by ocramz — COMMENTED** [review]
It's a good change overall but I'd rather keep imports explicit and docstrings clearer.

File: Web/Scotty/Action.hs (hunk 3 above)
Comment (fumieval) [reply Web/Scotty/Action.hs:145]: Is your suggestion to decode lazily?

File: Web/Scotty/Action.hs (hunk 4 above)
Comment (fumieval) [reply Web/Scotty/Action.hs:350]: In order to throw an exception. What's wrong with it?

File: Web/Scotty/Action.hs (hunk 3 above)
Comment (fumieval) [reply Web/Scotty/Action.hs]: I switched to use `raw` instead

File: Web/Scotty/Action.hs (hunk 2 above)
Comment (fumieval) [reply Web/Scotty/Action.hs]: I removed the word

File: Web/Scotty/Action.hs (hunk 4 above)
Comment (ocramz) [reply Web/Scotty/Action.hs:350]: Nothing per se, but if the underlying implementation didn't change why change the type sig?

File: Web/Scotty/Internal/Types.hs [hunk 6]
```diff
@@ -231,10 +239,11 @@ instance (MonadUnliftIO m) => MonadPlus (ActionT m) where
 
 -- | catches either ActionError (thrown by 'next') or 'StatusError' (thrown if e.g. a query parameter is not found)
```
Comment (ocramz) [inline Web/Scotty/Internal/Types.hs:240]: the docstring should be updated to show that we also catch 'ScottyException' here

File: Web/Scotty/Action.hs (hunk 4 above)
Comment (fumieval) [reply Web/Scotty/Action.hs:350]: The underlying implementation did change, namely `paramWith` now requires MonadIO because it calls `throwIO` instead of `throw`. In general it's a good practice to avoid throwing an exception in a pure context.

File: Web/Scotty/Internal/Types.hs (hunk 6 above)
Comment (fumieval) [reply Web/Scotty/Internal/Types.hs]: done

**Comment by fumieval** [comment]
@ocramz Do you have any remaining concerns?

File: Web/Scotty/Action.hs (hunk 4 above)
Comment (ocramz) [reply Web/Scotty/Action.hs:350]: @fumieval  ^

**Review by ocramz — CHANGES_REQUESTED** [review]
It's a good PR, but I still think `captureParamMaybe` doesn't need the MonadIO constraint.

Also, shouldn't we add a deprecation warning to `raiseStatus`?

File: Web/Scotty/Action.hs (hunk 4 above)
Comment (fumieval) [reply Web/Scotty/Action.hs]: OK, fixed

**Comment by fumieval** [comment]
I'm going to deprecate `raiseStatus` in a separate PR.

**Comment by fumieval** [comment]
@ocramz ping

**Comment by ocramz** [comment]
Hi @fumieval! I haven't forgotten about this, it's just that I'm on a
family holiday until the end of the month. Will look at it then! Best, Marco

**Review by ocramz — COMMENTED** [review]
Great, thank you! 👍

**Review by ocramz — APPROVED** [review]

**Comment by ocramz** [comment]
@fumieval  could you add a Changelog entry about this as well please?
